### ISSUE TITLE
State format has changed

### ISSUE THREAD

**Issue by JoernSeltmann** [zdazzy/eg-pyms-lan#1]
There seems to have been a change in the state format. The protocol has been updated to v2.1 and the format is now:

"Control and state format:

stat[i]=0x41 – voltage is present on socket i+1
stat[i]=0x82 - voltage is absent on socket i+1"

Thanks for providing the script!

**Comment by zdazzy** [comment]
unfortunately I cannot verify this as mine is still controlled alright with the current script. the chances I would bother with it again are very slim so feel free to fork the repo and fix this.
