### ISSUE TITLE
Extract Rest Requests?

### ISSUE THREAD

**Issue by srissel** [zdazzy/eg-pyms-lan#4]
Hello,

thanks for this well working Python script! It's a lot easier to control the power device with such a small command client...

I am working on a similar project: I would like to write an mobile (resonsive) web application, with which I can control the device from desktop, smartphone, all by the same application.
To get this startet, I try to debug the rest requests necessary, using the web frontend and the browser's developer tools and try to emulate them from a rest client, using the same parameters.
Unfortunately, my POST requests do not yield any answer from the server; they all run into a timeout.

I am not familiar with python, so reading your script doesn't provide the necessary information to me.
Do you have any hints about what might be my problem, why my POST requests all run into a timeout?
the obvious parameters (host, http headers, form data) all seem correct....

Thanks in advance,
Sascha.

**Comment by zdazzy** [comment]
You need to elaborate more on what exactly you are doing and what your goal is.

**Comment by srissel** [comment]
Okay, in Short Terms:
I'd like to read the current socket states and display them to the User and also allow the user to activatele and deactivate individual sockets on demand.

I hope this explains my goal...

**Comment by srissel** [comment]
It shall either be done via Ajax or PHP Rest requests.

**Comment by zdazzy** [comment]
There are no REST services on the device itself, just plain old HTTP. Just do your required actions manually in the browser, record produced GETs/POSTs and replicate them in your client.
If you want your client to use REST, you'll have to create an additional layer of abstraction.

**Comment by srissel** [comment]
Many thanks for you hints.
I was able to figure out the necessary request and I'm building my own request layer.
